version: '3'
services:
 web:
   container_name: catidea
   build: .
   command: python3 manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
     - 18000:8000
   volumes:
     - .:/code
   depends_on:
     - db
 db:
   image: postgres
   ports:
     - "5432"
   environment:
     - POSTGRES_DB:postgres
     - POSTGRES_USER:postgres
     - POSTGRES_PASSWORD:postgres
   
